# API Keys
DEEPSEEK_API_KEY = "sk-de2e0a036eea413bae3803b1a85afb34"
GEMINI_API_KEY = "AIzaSyC_6ToOp1Q6cEwwrJIhQnTOYmt33FgWITU"
GEMINI_OPERATIONS_KEY = "AIzaSyB-kbXJJ-HDW2jmqNBBz0JRo9nM6qRfbNs"
GEMINI_SUPERVISOR_KEY = "AIzaSyC_6ToOp1Q6cEwwrJIhQnTOYmt33FgWITU"
GEMINI_INVENTORY_KEY = "AIzaSyC_6ToOp1Q6cEwwrJIhQnTOYmt33FgWITU"
